### PR TITLE
Add method to get the users of a specific group.

### PR DESCRIPTION
**Pull request by flyinprogrammer**

### CODE REVIEW

**Comment by diclophis** [comment]
This would be extremely useful for our purposes as well, please merge as soon as possible

**Comment by tbelote-okta** [comment]
Sorry for the long delay in responding, a contributor license agreement process is coming soon and we will be reaching out to accept this PR.

**Comment by flyinprogrammer** [comment]
ACK - just let me know what to sign.

**Comment by diclophis** [comment]
Great

**Pull request merged**
